name: Build LaTeX PDFs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install poppler-utils
      run: sudo apt-get install -y poppler-utils

    - name: Compile LaTeX documents
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace danteev/texlive bash -c "find . -name '*.tex' -exec latexmk -pdf -interaction=nonstopmode -file-line-error {} \;"
    
    - name: Move PDFs to resume_pdfs directory
      run: |
        mkdir -p resume_pdfs
        find . -name '*.pdf' -exec mv {} resume_pdfs/ \;

    - name: Convert PDFs to PNG images
      run: |
        mkdir -p resume_images
        for pdf_file in resume_pdfs/*.pdf; do
          base_name=$(basename "$pdf_file" .pdf)
          pdftoppm -png -f 1 -singlefile "$pdf_file" "resume_images/${base_name}.png"
        done

    - name: Commit PDFs and PNG images
      run: |
        git config --local user.email "action[bot]@github.com"
        git config --local user.name "github-actions[bot]"
        git add resume_pdfs/*.pdf resume_images/*.png
        git commit -m "[bot] updated resume pdfs and images" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
