name: Build LaTeX PDFs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Compile LaTeX documents
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace danteev/texlive bash -c "find . -name '*.tex' -exec latexmk -pdf -interaction=nonstopmode -file-line-error {} \;"

    - name: Upload PDFs
      uses: actions/upload-artifact@v2
      with:
        name: latex-pdfs
        path: '**/*.pdf'
