name: Build LaTeX PDFs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Compile LaTeX documents
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace danteev/texlive bash -c "find . -name '*.tex' -exec latexmk -pdf -interaction=nonstopmode -file-line-error {} \;"
    
    - name: Move PDFs to resume_pdfs directory
      run: |
        mkdir -p resume_pdfs
        find . -name '*.pdf' -exec mv {} resume_pdfs/ \;

    - name: Commit PDFs
      run: |
        git config --local user.email "action[bot]@github.com"
        git config --local user.name "github-actions[bot]"
        git add resume_pdfs/*.pdf
        git commit -m "[bot] updated resume pdfs" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
